/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/invites': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Invites */
    get: operations['list_invites_invites_get']
    put?: never
    /** Create Invite */
    post: operations['create_invite_invites_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/invites/{invite_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Revoke Invite */
    delete: operations['revoke_invite_invites__invite_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/matchup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Matchup */
    get: operations['matchup_matchup_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_me_get']
    put?: never
    post?: never
    /** Delete Me */
    delete: operations['delete_me_me_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/draft-settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Draft Settings */
    get: operations['get_draft_settings_me_draft_settings_get']
    /** Put Draft Settings */
    put: operations['put_draft_settings_me_draft_settings_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export */
    get: operations['export_me_export_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Settings */
    get: operations['get_settings_me_settings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Patch Settings */
    patch: operations['patch_settings_me_settings_patch']
    trace?: never
  }
  '/me/sims': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Sims */
    get: operations['list_sims_me_sims_get']
    put?: never
    /** Save Sim */
    post: operations['save_sim_me_sims_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/sims/{sim_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Sim */
    get: operations['get_sim_me_sims__sim_id__get']
    /**
     * Update League
     * @description A replay league as it progresses (weeks kept, roster): compare-and-set on its version.
     */
    put: operations['update_league_me_sims__sim_id__put']
    post?: never
    /** Delete Sim */
    delete: operations['delete_sim_me_sims__sim_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/me/sims/{sim_id}/pin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Pin Sim */
    patch: operations['pin_sim_me_sims__sim_id__pin_patch']
    trace?: never
  }
  '/me/telegram/link': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Telegram Link */
    post: operations['telegram_link_me_telegram_link_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Members */
    get: operations['list_members_members_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/members/{uid}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Member */
    delete: operations['remove_member_members__uid__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/players': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Players */
    get: operations['players_players_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/replay/seasons': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Replay Seasons */
    get: operations['replay_seasons_replay_seasons_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/replay/{season}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Replay Season */
    get: operations['replay_season_replay__season__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/system/freshness': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Freshness */
    get: operations['freshness_system_freshness_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/system/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_system_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Today */
    get: operations['today_today_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/waivers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Waivers */
    get: operations['waivers_waivers_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AccountExport */
    AccountExport: {
      draftSettings: components['schemas']['DraftSettings']
      profile: components['schemas']['Member']
      settings: components['schemas']['UserSettings']
      /**
       * Sims
       * @default []
       */
      sims: components['schemas']['SimFull'][]
    }
    /** Action */
    Action: {
      /** Confidence */
      confidence?: ('high' | 'medium' | 'low') | null
      /** Cta */
      cta?: string | null
      /** Deadline */
      deadline?: string | null
      /** Detail */
      detail: string
      /** Id */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'lineup' | 'injury' | 'stream'
      /** Title */
      title: string
      /** Why */
      why: string[]
    }
    /**
     * Badge
     * @description WEB-018: a short label with the stored numbers it was decided on.
     */
    Badge: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'injured_today'
        | 'adjusted'
        | 'injury_prone'
        | 'missed_time'
        | 'breakout'
        | 'bounce_back'
        | 'rookie'
        | 'top_tier'
      /** Label */
      label: string
      /**
       * Tone
       * @enum {string}
       */
      tone: 'neutral' | 'accent' | 'win' | 'lose' | 'warn'
      /** Why */
      why: string
    }
    /** CategoryProjection */
    CategoryProjection: {
      /** Code */
      code: string
      /** Mine */
      mine: string
      /** Note */
      note?: string | null
      /** Theirs */
      theirs: string
      /** Winprob */
      winProb: number
    }
    /** DraftFx */
    DraftFx: {
      /**
       * Motion
       * @enum {string}
       */
      motion: 'auto' | 'reduced'
      /** Sound */
      sound: boolean
      /**
       * Tick
       * @enum {string}
       */
      tick: 'off' | 'last10' | 'every'
      /** Volume */
      volume: number
    }
    /** DraftLeague */
    DraftLeague: {
      /**
       * Budget
       * @description Auction budget 50..1000; null for a snake draft
       */
      budget: number | null
      /**
       * Categories
       * @description Category formats: a subset of the stats
       */
      categories?: string[] | null
      /**
       * Drafting
       * @enum {string}
       */
      drafting: 'auction' | 'snake'
      scoring: components['schemas']['ScoringFormat']
      /**
       * Seat
       * @description 1..teams; used by snake only
       */
      seat: number
      /** Spots */
      spots: number
      /** Teams */
      teams: number
      /**
       * Weights
       * @description Points formats: stat -> points
       */
      weights?: {
        [key: string]: number
      } | null
    }
    /** DraftPreset */
    DraftPreset: {
      /**
       * Id
       * @description 1..40 of A-Za-z0-9_-
       */
      id: string
      league: components['schemas']['DraftLeague']
      /**
       * Name
       * @description 1..40 characters, unique ignoring case
       */
      name: string
      room: components['schemas']['DraftRoom']
      /**
       * Season
       * @description current, or like 2025-26
       */
      season: string
      strategy: components['schemas']['DraftStrategy']
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string
    }
    /** DraftRoom */
    DraftRoom: {
      /** Bidseconds */
      bidSeconds: number
      /** Nominateseconds */
      nominateSeconds: number
      /**
       * Pace
       * @enum {string}
       */
      pace: 'real' | 'fast' | 'untimed' | 'custom'
      /**
       * Styles
       * @enum {string}
       */
      styles: 'mix' | 'balanced' | 'stars' | 'punter' | 'value'
    }
    /**
     * DraftSettings
     * @description The saved document. PUT it back whole with If-Match: the ETag from GET /me/draft-settings.
     */
    DraftSettings: {
      /**
       * Activeid
       * @description The preset the setup page starts with; null = built-in
       */
      activeId: string | null
      fx: components['schemas']['DraftFx']
      /** Presets */
      presets: components['schemas']['DraftPreset'][]
      /**
       * Version
       * @description 0 until first saved; the ETag carries it too. Ignored on PUT: If-Match decides
       */
      version: number
    }
    /** DraftStrategy */
    DraftStrategy: {
      /**
       * Punt
       * @description null, or one of the league's category codes
       */
      punt: string | null
    }
    /** Freshness */
    Freshness: {
      /** Asof */
      asOf: string | null
      /** Sources */
      sources: components['schemas']['Source'][]
      /** Stalesince */
      staleSince?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Health */
    Health: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /**
     * Indicator
     * @description WEB-020: a decision indicator with the stored numbers behind it.
     */
    Indicator: {
      /**
       * Code
       * @enum {string}
       */
      code: 'range' | 'certainty' | 'role' | 'punt_fit' | 'consistency' | 'age'
      /** Label */
      label: string
      /**
       * Signal
       * @default false
       */
      signal: boolean
      /**
       * Tone
       * @enum {string}
       */
      tone: 'neutral' | 'accent' | 'win' | 'lose' | 'warn'
      /** Value */
      value?: number | null
      /** Why */
      why: string
    }
    /** Invite */
    Invite: {
      /** Claimedat */
      claimedAt: string | null
      /** Claimedby */
      claimedBy: string | null
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Createdby */
      createdBy: string
      /** Email */
      email: string
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Id */
      id: string
      /**
       * Role
       * @enum {string}
       */
      role: 'owner' | 'member'
      /**
       * Status
       * @enum {string}
       */
      status: 'open' | 'expired' | 'claimed'
    }
    /** InviteCreate */
    InviteCreate: {
      /** Email */
      email: string
      /**
       * Role
       * @default member
       * @enum {string}
       */
      role: 'owner' | 'member'
    }
    /** JobFreshness */
    JobFreshness: {
      /** Job */
      job: string
      /**
       * Lastrun
       * Format: date-time
       */
      lastRun: string
      /** Laststatus */
      lastStatus: string
      /** Lastsuccess */
      lastSuccess: string | null
    }
    /** Matchup */
    Matchup: {
      /** Categories */
      categories: components['schemas']['CategoryProjection'][]
      /** Daysleft */
      daysLeft: number
      /** Expectedcategories */
      expectedCategories: number
      freshness: components['schemas']['Freshness']
      /** Opponent */
      opponent: string | null
      record?: components['schemas']['Record'] | null
      /**
       * Weekend
       * Format: date
       */
      weekEnd: string
      /**
       * Weekstart
       * Format: date
       */
      weekStart: string
    }
    /** Me */
    Me: {
      /** Displayname */
      displayName: string | null
      /** Email */
      email: string
      /**
       * Role
       * @enum {string}
       */
      role: 'owner' | 'member'
      /** Uid */
      uid: string
    }
    /** Member */
    Member: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Displayname */
      displayName: string | null
      /** Email */
      email: string
      /**
       * Lastseenat
       * Format: date-time
       */
      lastSeenAt: string
      /**
       * Role
       * @enum {string}
       */
      role: 'owner' | 'member'
      /** Uid */
      uid: string
    }
    /**
     * PlayerProjection
     * @description Projected per-game averages for the season (the draft model, DRAFT-008).
     */
    PlayerProjection: {
      /** Ast */
      ast: number
      /** Blk */
      blk: number
      /** Fg3M */
      fg3m: number
      /** Fgpct */
      fgPct: number | null
      /** Ftpct */
      ftPct: number | null
      /** Games */
      games: number
      /** Mpg */
      mpg: number
      /** Pts */
      pts: number
      /** Reb */
      reb: number
      /** Stl */
      stl: number
      /** Tov */
      tov: number
    }
    /** PlayerRow */
    PlayerRow: {
      /** Badges */
      badges?: components['schemas']['Badge'][]
      /** Dollars */
      dollars: number
      /** Healthydollars */
      healthyDollars?: number | null
      /** Healthyrank */
      healthyRank?: number | null
      /** Id */
      id: number
      /** Inpool */
      inPool: boolean
      /** Indicators */
      indicators?: components['schemas']['Indicator'][]
      /** Name */
      name: string
      /** Positions */
      positions: string | null
      projection: components['schemas']['PlayerProjection'] | null
      /** Rank */
      rank: number
      signal?: components['schemas']['Indicator'] | null
      /** Status */
      status: string | null
      /** Strengths */
      strengths: {
        [key: string]: number
      }
      /** Team */
      team: string | null
      /** Tier */
      tier: number
      /** Value */
      value: number
    }
    /** Players */
    Players: {
      /** Badgenotes */
      badgeNotes?: string[]
      freshness: components['schemas']['Freshness']
      /** Players */
      players: components['schemas']['PlayerRow'][]
      /** Variant */
      variant: string
      /** Variants */
      variants: string[]
    }
    /** Product */
    Product: {
      /** Asof */
      asOf: string | null
      /** Name */
      name: string
    }
    /** Record */
    Record: {
      /** Losses */
      losses: number
      /** Ties */
      ties: number
      /** Wins */
      wins: number
    }
    /** ReplaySeasons */
    ReplaySeasons: {
      /** Seasons */
      seasons: string[]
    }
    /**
     * ScoringFormat
     * @enum {string}
     */
    ScoringFormat: 'h2h_categories' | 'h2h_one_win' | 'rotisserie' | 'h2h_points' | 'season_points'
    /**
     * SettingsPatch
     * @description Only the fields sent change. Send with If-Match: the ETag from GET /me/settings.
     */
    SettingsPatch: {
      /** Alerts */
      alerts?: string[] | null
      /** Awakeend */
      awakeEnd?: string | null
      /** Awakestart */
      awakeStart?: string | null
      /** Briefenabled */
      briefEnabled?: boolean | null
      /** Displayname */
      displayName?: string | null
      /** Draftstrategy */
      draftStrategy?: string | null
      /** Theme */
      theme?: string | null
      /** Timezone */
      timeZone?: string | null
    }
    /** SimFull */
    SimFull: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Detail */
      detail: {
        [key: string]: unknown
      } | null
      /**
       * Hasdetail
       * @description False once an old practice run is trimmed to its summary
       */
      hasDetail: boolean
      /** Id */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'practice' | 'league'
      /** Pinned */
      pinned: boolean
      /** Season */
      season: string
      /** Summary */
      summary: {
        [key: string]: unknown
      }
      /** Title */
      title: string
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string
      /** Version */
      version: number
    }
    /**
     * SimIn
     * @description A finished practice draft or a new replay league. `id` is the client's (idempotent).
     */
    SimIn: {
      /**
       * Detail
       * @description The full run or league (≤ 256 KB)
       */
      detail: {
        [key: string]: unknown
      }
      /** Id */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'practice' | 'league'
      /** Season */
      season: string
      /**
       * Summary
       * @description Small (≤ 4 KB): what the list shows
       */
      summary: {
        [key: string]: unknown
      }
      /** Title */
      title: string
    }
    /** SimPin */
    SimPin: {
      /** Pinned */
      pinned: boolean
    }
    /** SimSummary */
    SimSummary: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /**
       * Hasdetail
       * @description False once an old practice run is trimmed to its summary
       */
      hasDetail: boolean
      /** Id */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'practice' | 'league'
      /** Pinned */
      pinned: boolean
      /** Season */
      season: string
      /** Summary */
      summary: {
        [key: string]: unknown
      }
      /** Title */
      title: string
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string
      /** Version */
      version: number
    }
    /** SimUpdate */
    SimUpdate: {
      /** Detail */
      detail: {
        [key: string]: unknown
      }
      /** Summary */
      summary: {
        [key: string]: unknown
      }
      /** Title */
      title: string
    }
    /** Source */
    Source: {
      /** Asof */
      asOf: string | null
      /** Name */
      name: string
    }
    /** SystemFreshness */
    SystemFreshness: {
      /** Jobs */
      jobs: components['schemas']['JobFreshness'][]
      /** Products */
      products: components['schemas']['Product'][]
    }
    /** TelegramLink */
    TelegramLink: {
      /** Code */
      code: string
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Instructions */
      instructions: string
    }
    /** Today */
    Today: {
      /** Actions */
      actions: components['schemas']['Action'][]
      /**
       * Date
       * Format: date
       */
      date: string
      freshness: components['schemas']['Freshness']
      matchup: components['schemas']['Matchup'] | null
    }
    /** UserSettings */
    UserSettings: {
      /** Alerts */
      alerts: ('brief' | 'injury' | 'waiver')[]
      /**
       * Awakeend
       * @description HH:MM, 24-hour, in time_zone
       */
      awakeEnd: string
      /**
       * Awakestart
       * @description HH:MM, 24-hour, in time_zone
       */
      awakeStart: string
      /** Briefenabled */
      briefEnabled: boolean
      /** Displayname */
      displayName: string | null
      /**
       * Draftstrategy
       * @description all, or punt_<category>
       */
      draftStrategy: string
      /** Telegramlinked */
      telegramLinked: boolean
      /**
       * Theme
       * @enum {string}
       */
      theme: 'system' | 'light' | 'dark'
      /** Timezone */
      timeZone: string
      /**
       * Version
       * @description 0 until first saved; the ETag carries it too
       */
      version: number
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** WaiverCandidate */
    WaiverCandidate: {
      /** Gain */
      gain: number
      /** Gamesleft */
      gamesLeft: number
      /** Helps */
      helps: string[]
      /** Id */
      id: string
      /** Name */
      name: string
      /** Positions */
      positions?: string | null
      /** Team */
      team?: string | null
    }
    /** Waivers */
    Waivers: {
      /** Candidates */
      candidates: components['schemas']['WaiverCandidate'][]
      freshness: components['schemas']['Freshness']
      /**
       * Horizon
       * @default this week
       */
      horizon: string
      /** Suggesteddrop */
      suggestedDrop: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_invites_invites_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Invite'][]
        }
      }
    }
  }
  create_invite_invites_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteCreate']
      }
    }
    responses: {
      /** @description An open invite for this email already existed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Invite']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  revoke_invite_invites__invite_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  matchup_matchup_get: {
    parameters: {
      query?: {
        day?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Matchup']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Me']
        }
      }
    }
  }
  delete_me_me_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The last owner can't delete their account */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_draft_settings_me_draft_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DraftSettings']
        }
      }
    }
  }
  put_draft_settings_me_draft_settings_put: {
    parameters: {
      query?: never
      header?: {
        'if-match'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftSettings']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DraftSettings']
        }
      }
      /** @description Changed elsewhere: the body's `current` is the stored document */
      412: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Over 16 KB */
      413: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A field failed validation: `field` is its path */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description If-Match is required */
      428: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  export_me_export_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountExport']
        }
      }
    }
  }
  get_settings_me_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserSettings']
        }
      }
    }
  }
  patch_settings_me_settings_patch: {
    parameters: {
      query?: never
      header?: {
        'if-match'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingsPatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserSettings']
        }
      }
      /** @description Changed elsewhere: the body's `current` is the stored document */
      412: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description If-Match is required */
      428: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_sims_me_sims_get: {
    parameters: {
      query?: {
        kind?: ('practice' | 'league') | null
        season?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimSummary'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  save_sim_me_sims_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SimIn']
      }
    }
    responses: {
      /** @description Already saved (same id): the stored copy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimFull']
        }
      }
      /** @description too-many-leagues */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Over 256 KB */
      413: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_sim_me_sims__sim_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        sim_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimFull']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_league_me_sims__sim_id__put: {
    parameters: {
      query?: never
      header?: {
        'if-match'?: string | null
      }
      path: {
        sim_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SimUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimFull']
        }
      }
      /** @description Changed elsewhere: the body's `current` is the stored copy */
      412: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description If-Match is required */
      428: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_sim_me_sims__sim_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        sim_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  pin_sim_me_sims__sim_id__pin_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        sim_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SimPin']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SimSummary']
        }
      }
      /** @description too-many-pins */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  telegram_link_me_telegram_link_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TelegramLink']
        }
      }
    }
  }
  list_members_members_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Member'][]
        }
      }
    }
  }
  remove_member_members__uid__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        uid: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  players_players_get: {
    parameters: {
      query?: {
        variant?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Players']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  replay_seasons_replay_seasons_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReplaySeasons']
        }
      }
    }
  }
  replay_season_replay__season__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        season: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The season document */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  freshness_system_freshness_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemFreshness']
        }
      }
    }
  }
  health_system_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  today_today_get: {
    parameters: {
      query?: {
        day?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Today']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  waivers_waivers_get: {
    parameters: {
      query?: {
        day?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Waivers']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
